--- #Delimits each Cloud Environment
datacenters:
  - !datacenter
    name:
    amount: 2
    vmAllocationPolicy: Simple
    architecture: x86
    os: Linux
    vmm: Xen
    upperUtilizationThreshold: 0.8
    lowerUtilizationThreshold: 0.2
    vmMigration: enabled
    schedulingInterval: 30
    costPerSec: 0.1
    costPerMem: 0.05
    costPerStorage: 0.001
    costPerBw: 0.1
    sans:
      - !san
        name: san1
        capacity: 100000
        bandwidth: 10000
        networkLatency: 5
    hosts:
      - !host
        amount: 4
        ram: 1000000
        bw: 10000
        storage: 40000
        maxPower: 250
        staticPowerPercent: 0.7
        pes: 4
        mips: 1000
        vmScheduler: TimeShared
        powerModel: Linear
        ramProvisioner: Simple
        bwProvisioner: Simple
        peProvisioner: Simple
customers:
  - !customer
    name:
    amount: 4
    vms:
      - !vm
        amount: 4
        size: 500
        pes: 2
        mips: 1000
        ram: 2000
        bw: 100
        priority: 1
        vmm: Xen
        cloudletScheduler: TimeShared
    cloudlets:
      - !cloudlet
        amount: 2
        pes: 2
        length: 1000
        fileSize: 50
        outputSize: 50
        utilizationModelCpu: Full
        utilizationModelRam: Full
        utilizationModelBw: Full
      - !cloudlet
        amount: 2
        pes: 2
        length: 2000
        fileSize: 50
        outputSize: 50
        utilizationModelCpu: Full
        utilizationModelRam: Full
        utilizationModelBw: Full        